from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
RESULTS_DIR = ROOT / "results"
MODELS_DIR = ROOT / "models"

CATALOG_CSV = DATA_DIR / "galaxies.csv"
DENSITY_NPY = DATA_DIR / "density_grid.npy"
POSITIONS_NPY = DATA_DIR / "positions_mpc.npy"
CLUSTER_LABELS_NPY = DATA_DIR / "cluster_labels.npy"
VOID_MASK_NPY = DATA_DIR / "void_mask.npy"
FILAMENT_MASK_NPY = DATA_DIR / "filament_mask.npy"

MAX_GALAXIES = 30_000
Z_MIN = 0.01
Z_MAX = 0.25

GRID_SIZE = 64

DBSCAN_EPS_MPC = 8.0
DBSCAN_MIN_SAMPLES = 12
VOID_DENSITY_PERCENTILE = 15.0
FILAMENT_DENSITY_PERCENTILE = 85.0
CORRELATION_SUBSAMPLE = 4_000
CORRELATION_MAX_RADIUS_MPC = 80.0
CORRELATION_NBINS = 40
CORRELATION_RANDOM_TRIALS = 3

PATCH_SIZE = 16
LATENT_DIM = 32
AUTOENCODER_EPOCHS = 25
BATCH_SIZE = 16
RANDOM_SEED = 42

FIGURE_DPI = 200
PLOT_SUBSAMPLE = 12_000
